export {
  completeSubsystemArchitecture,
  addSubsystemPart,
  confirmSubsystem,
  confirmSubsystemRequirement,
  createSubsystem,
  createSubsystemRequirement,
  deleteSubsystemRequirement,
  generateAllSubsystemRequirements,
  generateSubsystemRequirements,
  generateSubsystems,
  getAllSubsystemRequirements,
  getReview,
  getSubsystemDetails,
  getSubsystemInterface,
  getSubsystemInterfaceEvidence,
  getSubsystemInterfaces,
  getSubsystemPorts,
  getSubsystemRequirementCoverage,
  getSubsystemReadiness,
  getSubsystemRequirementsBySubsystemId,
  getSubsystems,
  markDesignComplete,
  mergeSubsystems,
  moveSubsystemPart,
  regenerateStaleSubsystemRequirements,
  removeSubsystemPart,
  rejectSubsystem,
  rejectSubsystemInterface,
  rejectSubsystemRequirement,
  splitSubsystem,
  confirmSubsystemInterface,
  updateSubsystem,
  updateSubsystemInterface,
  updateSubsystemRequirement,
} from './legacy';

export type {
  GenerateSubsystemRequirementsResponse,
  ReviewResponse,
  ReviewSubsystem,
  SubsystemCreatePayload,
  SubsystemDetailsResponse,
  SubsystemInterfaceContract,
  SubsystemInterfaceEvidence,
  SubsystemMergePayload,
  SubsystemPartDetail,
  SubsystemPort,
  SubsystemReadinessItem,
  SubsystemReadinessResponse,
  SubsystemRequirementCoverageResponse,
  SubsystemRequirementItem,
  SubsystemRequirementsResponse,
  SubsystemSplitPayload,
  SubsystemsResponse,
  SubsystemSummary,
} from './legacy';
