export {
  completeSubsystemArchitecture,
  confirmSubsystem,
  confirmSubsystemRequirement,
  createSubsystemRequirement,
  deleteSubsystemRequirement,
  generateAllSubsystemRequirements,
  generateSubsystemRequirements,
  generateSubsystems,
  getAllSubsystemRequirements,
  getReview,
  getSubsystemDetails,
  getSubsystemReadiness,
  getSubsystemRequirementsBySubsystemId,
  getSubsystems,
  markDesignComplete,
  moveSubsystemPart,
  rejectSubsystem,
  rejectSubsystemRequirement,
  updateSubsystem,
  updateSubsystemInterface,
  updateSubsystemRequirement,
} from './legacy';

export type {
  GenerateSubsystemRequirementsResponse,
  ReviewResponse,
  ReviewSubsystem,
  SubsystemDetailsResponse,
  SubsystemPartDetail,
  SubsystemReadinessItem,
  SubsystemReadinessResponse,
  SubsystemRequirementItem,
  SubsystemRequirementsResponse,
  SubsystemsResponse,
  SubsystemSummary,
} from './legacy';
